### ISSUE TITLE
Conflicts with AdvancedSubclasses

### ISSUE THREAD

**Issue by aurelienblais** [gamehunt/CustomNPCs#2]
Hello !

We just found a compat problem with AdvancedSubclasses.
One of the abilities AS allow us to give is `Disable096Trigger` which won't work if CustomNPCs is also on the server.

Thanks :)

**Comment by gamehunt** [comment]
We patch the same `Scp096.UpdateVision` method, it is the problem. I think I can try to fix it by moving my patch to the different location, but Im unsure if there is such possibility;

**Comment by steven4547466** [comment]
~~I'm switching to an IL patch in the future so you shouldn't have to worry.~~

This won't fix it because the prefix always returns false anyways. So I'm not sure how it'd work.

**Comment by gamehunt** [comment]
Fixed
