### ISSUE TITLE
Found a few bugs

### ISSUE THREAD

**Issue by tpd1864blake** [gamehunt/CustomNPCs#6]
I've been creating NPCs to mess around and test the limits of this plugin, and I found the following bugs

- [ ] NPCs walk through LCZ checkpoints and airlocks without opening them
- [ ] NPCs spawned at the end of CDC and in 049's room past the elevator cannot move
- [ ] AINavigateToRoom does not work properly unless room is set to "random"
- [ ] AIFindItemTarget does not work at all
- [ ] SCP-049 breaks after killing another NPC
- [ ] SCP-096 does not become enraged when a valid target is found and they view his face, additionally they will not pathfind to kill their target. You must step in front of them to be killed
- [ ] Most NPCs (with some exceptions) instructed to attack targets become frozen as soon as they lose their target (sometimes after they kill them, such as 049, 096, 939, etc.)
- [ ] NPCs do not stop at tesla gates and instead walk through while it is firing (no damage is taken)
- [ ] EndConditions compatibility module causes error on startup
- [ ] SCP-173 does not trigger blink and can move even while people are observing it
- [ ] Wearing SCP-268 does not impede NPC's ability to track and kill you

I'm never expecting this plugin to achieve human-like accuracy with NPCs, but nevertheless this is fun to mess around with when in a small server with friends (or by yourself if you create multiple NPCs and observe how they interact with each other). If you need me to send you stuff like error logs and config then I'll go ahead

Also the wiki should probably be updated, like what are the different AI types under the ai_mode value and a list of room names and other useful stuff like that

**Comment by gamehunt** [comment]
Closed due to plugin was archived
